apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: projectxx-gitops-app
  namespace: flux-system
spec:
  sourceRef:
    kind: GitRepository
    name: projectxx-repo
  interval: 10m
  path: ./manifests
  prune: true # This will make sure that deleting the file will delete the resource
  validation: client