apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectxx
  namespace: projectxx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectxx
  template:
    metadata:
      labels:
        app: projectxx
    spec:
      volumes:
        - name: shared-file-projectxx
          persistentVolumeClaim:
            claimName: projectxx-claim
      containers:
        - name: projectxx
          image: PROJECTXX/IMAGE
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /api/healthz
              port: 3000
          volumeMounts:
            - name: shared-file-projectxx
              mountPath: /usr/src/app/image
        - name: todo
          image: TODO/IMAGE
          livenessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /healthz
              port: 5000
          env:
            - name: BDPASSWORD 
              valueFrom:
                configMapKeyRef:
                  name: pojectxx-configmap
                  key: BDPASSWORD
            - name: BDUSER 
              valueFrom:
                configMapKeyRef:
                  name: pojectxx-configmap
                  key: BDUSER
            - name: BD
              valueFrom:
                configMapKeyRef:
                  name: pojectxx-configmap
                  key: BD
            - name: SERVICEROUTE
              valueFrom:
                configMapKeyRef:
                  name: pojectxx-configmap
                  key: SERVICEROUTE
            - name: PORT 
              valueFrom:
                configMapKeyRef:
                  name: pojectxx-configmap
                  key: PORT