apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yaml
  - persistencevolume.yaml
  - persistentvolumeclaim.yaml
  - statefulset.yaml
  - deployment.yaml
  - horizontalpodautoscaler.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: PROJECTXX/IMAGE
    newName: jc40/projectxx:6.1.3
  - name: TODO/IMAGE
    newName: jc40/todo:4.2.2
