apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: projectxx-claim
  namespace: projectxx
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi