apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: http-hc-config-projectxx
  namespace: projectxx
spec:
  healthCheck:
    checkIntervalSec: 15
    port: 3000
    type: HTTP
    requestPath: /api/healthz